secrets:
  MY_PASSWORD:
    value : "devanshgay"
    enabled :true
  GMAIL_PASSWORD:
    value : "hahapassworddekhega"
    enabled :true #means agent can see this 
  #GMAIL_PASSWORD = "hahapassworddekhega" #BOTH ABOVE AND THIS ARE SAME , JUST htis is more simpler way

  OLD_PASSWORD:
    value : "purana oass" #isko delete bhi kar sakte the  , par taki save rakhe aur future me kabhi use ho to dosable kiy ah , agnet cant aceess it  , its just like commented out code
    enabled : false

  API_KEY = "jdjhdsvhjsk"
